contract:
  rinkeby:
    account_name: 'rinkeby-account1'
    address: '0xC7Cbcc8a133532Ddbc7015ceFfaBC07477E4F899'
    winning_probability_in_promiles: 300
    dependencies:
      randomness:
        vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
        keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
        subscription_id: 638

networks:
  default: development
  development:
    cmd_settings:
      default_balance: 100

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.0

compiler:
  solc:
    version: 0.8.7
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'
