contract:
  rinkeby:
    account_name: 'rinkeby-account1'
    address: '0xA7fEe2a153C32e28914226D1CC9CDa27FA9194a9'
    winning_probability_in_promiles: 300
    dependencies:
      randomness:
        vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
        keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
        subscription_id: 638


dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.0

compiler:
  solc:
    version: 0.8.7
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'
